### ISSUE TITLE
Thanks, but..

### ISSUE THREAD

**Issue by NasmodorN** [TheValthos/L0ckb0x#1]
Hi,
First, Thanks for your works, pretty good hax !
"But" ;p
Everything works apart for the chests, doesn't appear on esp, don't know why?
Thanks in advance if you can fix it!
and thanks for your works again!

**Comment by TheValthos** [comment]
No problem ill look at the crates now,

**Comment by TheValthos** [comment]
fixed in latest Release. 

https://github.com/TheValthos/L0ckb0x/releases/tag/V1.1.1
