### ISSUE TITLE
Thanks for the update .. But.. ;p

### ISSUE THREAD

**Issue by NasmodorN** [TheValthos/L0ckb0x#2]
Hi again,
Thanks you ! Amazing job, fast update !!
*But* ;p
All chest and lootbox appear now, but it's ALL chest and lootbox location, it's not refresh. So hard to know if a chest is here or not,
Thanks in advance if you can fix this!
In any case, thanks for you awesome job!!!

**Comment by TheValthos** [comment]
I'll look at adding a refresh button

**Comment by TheValthos** [comment]
added refresh use F7
